name: Laravel CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, mysql

      - name: Run PHP lint
        run: find . -type f -name "*.php" -exec php -l {} \;

  test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: lint

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: erwe-surat
          MYSQL_USER: root
          MYSQL_PASSWORD:
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.testing
        run: cp .env.example .env.testing

      - name: Generate app key
        run: php artisan key:generate --env=testing

      - name: Link storage
        run: php artisan storage:link

      - name: Run migrations
        run: php artisan migrate --env=testing --force

      - name: Seed database
        run: php artisan db:seed --env=testing

      - name: Run tests
        run: php artisan test --env=testing
